"""update table

Revision ID: 1cf6df32ee4e
Revises: 
Create Date: 2023-06-13 15:11:12.334081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf6df32ee4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type_1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('type_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attack', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('defense', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sp_atk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sp_def', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('generation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('legendary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pokemon_pkey'),
    sa.UniqueConstraint('name', name='pokemon_name_key')
    )
    # ### end Alembic commands ###
