"""department table

Revision ID: 9c9d2549b284
Revises: c794290359f8
Create Date: 2023-06-13 16:34:33.814521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9d2549b284'
down_revision = 'c794290359f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('client_source', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('attack',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('defense',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sp_atk',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sp_def',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('speed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('generation',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('legendary',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('legendary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('generation',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('speed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sp_def',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sp_atk',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('defense',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('attack',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('department')
    # ### end Alembic commands ###
