"""added table fields

Revision ID: a81a683a98d7
Revises: 1cf6df32ee4e
Create Date: 2023-06-13 15:13:48.063720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81a683a98d7'
down_revision = '1cf6df32ee4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('attack',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('defense',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sp_atk',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sp_def',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('speed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('generation',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('legendary',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('legendary',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('generation',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('speed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sp_def',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sp_atk',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('defense',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('attack',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
