"""deleted some fields

Revision ID: c794290359f8
Revises: a81a683a98d7
Create Date: 2023-06-13 15:15:28.344803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c794290359f8'
down_revision = 'a81a683a98d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('sp_atk')
        batch_op.drop_column('sp_def')
        batch_op.drop_column('defense')
        batch_op.drop_column('speed')
        batch_op.drop_column('attack')
        batch_op.drop_column('generation')
        batch_op.drop_column('legendary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legendary', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('generation', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attack', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('speed', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('defense', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sp_def', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sp_atk', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
